mv ./src/main.jsx ./src/main.tsx
mv ./src/Map/MapEventer.jsx ./src/Map/MapEventer.tsx
mv ./src/Map/ActionsOnMapContext.jsx ./src/Map/ActionsOnMapContext.tsx
mv ./src/Map/PopupSwitchContext.jsx ./src/Map/PopupSwitchContext.tsx
mv ./src/Map/MapCoordinates.jsx ./src/Map/MapCoordinates.tsx
mv ./src/Map/Image/ImageMap.jsx ./src/Map/Image/ImageMap.tsx
mv ./src/Map/Image/ImagePlacementStretcher.jsx ./src/Map/Image/ImagePlacementStretcher.tsx
mv ./src/Map/Image/EmbeddedImageLayer.jsx ./src/Map/Image/EmbeddedImageLayer.tsx
mv ./src/Map/Image/StandaloneImageLayer.jsx ./src/Map/Image/StandaloneImageLayer.tsx
mv ./src/Map/RealMap.jsx ./src/Map/RealMap.tsx
mv ./src/Map/MapShower.jsx ./src/Map/MapShower.tsx
mv ./src/Map/AreaMarkListener.jsx ./src/Map/AreaMarkListener.tsx
mv ./src/Map/MarkedShape.jsx ./src/Map/MarkedShape.tsx
mv ./src/Map/MapDraw.jsx ./src/Map/MapDraw.tsx
mv ./src/Map/CustomIcon.jsx ./src/Map/CustomIcon.tsx
mv ./src/Map/Device/SingleDevicePropertiesView.jsx ./src/Map/Device/SingleDevicePropertiesView.tsx
mv ./src/Map/Device/DeviceMarker.jsx ./src/Map/Device/DeviceMarker.tsx
mv ./src/Map/Device/DeviceMarkersShown.jsx ./src/Map/Device/DeviceMarkersShown.tsx
mv ./src/Map/MapPositionOnUrl.jsx ./src/Map/MapPositionOnUrl.tsx
mv ./src/Map/MapPlacer.jsx ./src/Map/MapPlacer.tsx
mv ./src/Map/MapContextMenu.jsx ./src/Map/MapContextMenu.tsx
mv ./src/MapDraw/PolyEdit.jsx ./src/MapDraw/PolyEdit.tsx
mv ./src/MapDraw/MapDrawShape.jsx ./src/MapDraw/MapDrawShape.tsx
mv ./src/MapDraw/MapDrawExperiment.jsx ./src/MapDraw/MapDrawExperiment.tsx
mv ./src/MapDraw/CircleEdit.jsx ./src/MapDraw/CircleEdit.tsx
mv ./src/Utils/ButtonMenu.jsx ./src/Utils/ButtonMenu.tsx
mv ./src/Utils/TextFieldDebounce.jsx ./src/Utils/TextFieldDebounce.tsx
mv ./src/Utils/ButtonFile.jsx ./src/Utils/ButtonFile.tsx
mv ./src/Utils/ContextMenu.jsx ./src/Utils/ContextMenu.tsx
mv ./src/Utils/SwitchCase.jsx ./src/Utils/SwitchCase.tsx
mv ./src/Utils/ButtonTooltip.jsx ./src/Utils/ButtonTooltip.tsx
mv ./src/constants/icons.jsx ./src/constants/icons.tsx
mv ./src/IO/ImageOnServer.jsx ./src/IO/ImageOnServer.tsx
mv ./src/IO/UploadDevices/UploadDevicesButton.jsx ./src/IO/UploadDevices/UploadDevicesButton.tsx
mv ./src/IO/UploadDevices/UploadDevicesFieldsDialog.jsx ./src/IO/UploadDevices/UploadDevicesFieldsDialog.tsx
mv ./src/IO/UploadButton.jsx ./src/IO/UploadButton.tsx
mv ./src/IO/ErrorsDialog.jsx ./src/IO/ErrorsDialog.tsx
mv ./src/IO/DownloadExperimentButton.jsx ./src/IO/DownloadExperimentButton.tsx
mv ./src/IO/UploadImageButton.jsx ./src/IO/UploadImageButton.tsx
mv ./src/Icons/IconPicker.jsx ./src/Icons/IconPicker.tsx
mv ./src/Icons/DeviceIconLegend.jsx ./src/Icons/DeviceIconLegend.tsx
mv ./src/Property/DateProperty.jsx ./src/Property/DateProperty.tsx
mv ./src/Property/BooleanProperty.jsx ./src/Property/BooleanProperty.tsx
mv ./src/Property/SelectProperty.jsx ./src/Property/SelectProperty.tsx
mv ./src/Property/DateTimeProperty.jsx ./src/Property/DateTimeProperty.tsx
mv ./src/DeviceTable/DeviceTableRich.jsx ./src/DeviceTable/DeviceTableRich.tsx
mv ./src/DeviceTable/DeviceTable.jsx ./src/DeviceTable/DeviceTable.tsx
mv ./src/EditToolBox/ToolsBar/DistributeAlongArc.jsx ./src/EditToolBox/ToolsBar/DistributeAlongArc.tsx
mv ./src/EditToolBox/ToolsBar/DistributeAlongLine.jsx ./src/EditToolBox/ToolsBar/DistributeAlongLine.tsx
mv ./src/EditToolBox/ToolsBar/Rectangle.jsx ./src/EditToolBox/ToolsBar/Rectangle.tsx
mv ./src/EditToolBox/ToolsBar/FreePositioning.jsx ./src/EditToolBox/ToolsBar/FreePositioning.tsx
mv ./src/EditToolBox/ToolsBar/ButtonWithShadow.jsx ./src/EditToolBox/ToolsBar/ButtonWithShadow.tsx
mv ./src/EditToolBox/EditTool.jsx ./src/EditToolBox/EditTool.tsx
mv ./src/EditToolBox/ShapeContext.jsx ./src/EditToolBox/ShapeContext.tsx
mv ./src/EditToolBox/EditToolBox.jsx ./src/EditToolBox/EditToolBox.tsx
mv ./src/Experiment/TrialType.jsx ./src/Experiment/TrialType.tsx
mv ./src/Experiment/TrialTypesList.jsx ./src/Experiment/TrialTypesList.tsx
mv ./src/Experiment/AddMultipleDevices.jsx ./src/Experiment/AddMultipleDevices.tsx
mv ./src/Experiment/ExperimentRow.jsx ./src/Experiment/ExperimentRow.tsx
mv ./src/Experiment/AttributeItemList.jsx ./src/Experiment/AttributeItemList.tsx
mv ./src/Experiment/Contained/ContainedDevice.jsx ./src/Experiment/Contained/ContainedDevice.tsx
mv ./src/Experiment/Contained/AddContainedButton.jsx ./src/Experiment/Contained/AddContainedButton.tsx
mv ./src/Experiment/Shape/ShapeEditContent.jsx ./src/Experiment/Shape/ShapeEditContent.tsx
mv ./src/Experiment/Shape/ShapeItem.jsx ./src/Experiment/Shape/ShapeItem.tsx
mv ./src/Experiment/Shape/ShapeList.jsx ./src/Experiment/Shape/ShapeList.tsx
mv ./src/Experiment/Shape/ShapeColorPicker.jsx ./src/Experiment/Shape/ShapeColorPicker.tsx
mv ./src/Experiment/Shape/DrawShapeButton.jsx ./src/Experiment/Shape/DrawShapeButton.tsx
mv ./src/Experiment/SelectDeviceButton.jsx ./src/Experiment/SelectDeviceButton.tsx
mv ./src/Experiment/AttributeValue.jsx ./src/Experiment/AttributeValue.tsx
mv ./src/Experiment/AttributeTypesDialogButton.jsx ./src/Experiment/AttributeTypesDialogButton.tsx
mv ./src/Experiment/ExperimentTreeNodesExpandedProvider.jsx ./src/Experiment/ExperimentTreeNodesExpandedProvider.tsx
mv ./src/Experiment/Tabular/DevicesTabularView.jsx ./src/Experiment/Tabular/DevicesTabularView.tsx
mv ./src/Experiment/Tabular/DevicesTabularOneAttr.jsx ./src/Experiment/Tabular/DevicesTabularOneAttr.tsx
mv ./src/Experiment/Tabular/TrialsTabularView.jsx ./src/Experiment/Tabular/TrialsTabularView.tsx
mv ./src/Experiment/Tabular/DevicesTabularOneType.jsx ./src/Experiment/Tabular/DevicesTabularOneType.tsx
mv ./src/Experiment/Tabular/DevicesTabularOneDevice.jsx ./src/Experiment/Tabular/DevicesTabularOneDevice.tsx
mv ./src/Experiment/AttributeTypesDialog.jsx ./src/Experiment/AttributeTypesDialog.tsx
mv ./src/Experiment/DeviceType.jsx ./src/Experiment/DeviceType.tsx
mv ./src/Experiment/Trial.jsx ./src/Experiment/Trial.tsx
mv ./src/Experiment/ExperimentList.jsx ./src/Experiment/ExperimentList.tsx
mv ./src/Experiment/AddNewTrialButton.jsx ./src/Experiment/AddNewTrialButton.tsx
mv ./src/Experiment/DeviceTypesList.jsx ./src/Experiment/DeviceTypesList.tsx
mv ./src/Experiment/DeviceItem.jsx ./src/Experiment/DeviceItem.tsx
mv ./src/Experiment/ImageEmbedded.jsx ./src/Experiment/ImageEmbedded.tsx
mv ./src/Experiment/ImageStandalone.jsx ./src/Experiment/ImageStandalone.tsx
mv ./src/Experiment/EnclosedSelectionProvider.jsx ./src/Experiment/EnclosedSelectionProvider.tsx
mv ./src/App/AppHeader.jsx ./src/App/AppHeader.tsx
mv ./src/App/VersionId.jsx ./src/App/VersionId.tsx
mv ./src/App/LoginForm.jsx ./src/App/LoginForm.tsx
mv ./src/App/UserDetailsButton.jsx ./src/App/UserDetailsButton.tsx
mv ./src/App/AppHeaderButtons.jsx ./src/App/AppHeaderButtons.tsx
mv ./src/App/ShowConfigToggles.jsx ./src/App/ShowConfigToggles.tsx
mv ./src/App/App.jsx ./src/App/App.tsx
mv ./src/App/DevicePlanner.jsx ./src/App/DevicePlanner.tsx
mv ./src/Doc/DocumentationButton.jsx ./src/Doc/DocumentationButton.tsx
mv ./src/MapDraw/defaults.js ./src/MapDraw/defaults.ts
mv ./src/Utils/consoleErrorUniqueKeyFix.js ./src/Utils/consoleErrorUniqueKeyFix.ts
mv ./src/Utils/processingDecimalDigits.js ./src/Utils/processingDecimalDigits.ts
mv ./src/Utils/GeometryUtils.js ./src/Utils/GeometryUtils.ts
mv ./src/constants/constants.js ./src/constants/constants.ts
mv ./src/IO/FileIo.js ./src/IO/FileIo.ts
mv ./src/IO/TrialGeoJson.js ./src/IO/TrialGeoJson.ts
mv ./src/IO/CloneExperiment.js ./src/IO/CloneExperiment.ts
mv ./src/IO/UploadExperiment.js ./src/IO/UploadExperiment.ts
mv ./src/Icons/iconsCategories.js ./src/Icons/iconsCategories.ts
mv ./src/lib/Edit.SimpleShape.js ./src/lib/Edit.SimpleShape.ts
mv ./src/lib/Edit.Poly.js ./src/lib/Edit.Poly.ts
mv ./src/lib/Edit.Circle.js ./src/lib/Edit.Circle.ts
mv ./src/lib/Edit.Marker.js ./src/lib/Edit.Marker.ts
mv ./src/lib/Edit.CircleMarker.js ./src/lib/Edit.CircleMarker.ts
mv ./src/lib/Edit.Rectangle.js ./src/lib/Edit.Rectangle.ts
mv ./src/EditToolBox/utils/constants.js ./src/EditToolBox/utils/constants.ts
mv ./src/Experiment/AttributeValueGet.js ./src/Experiment/AttributeValueGet.ts
mv ./src/Context/TrackUuidUtils.js ./src/Context/TrackUuidUtils.ts
